version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
      cache_from:
        - "${BACKEND_IMAGE}"
    image: "${BACKEND_IMAGE}"
    command: gunicorn ambientDigital.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media
    expose:
      - 8000
    env_file: .env
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
