# Generated by Django 4.1.3 on 2022-11-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='quiz',
        ),
    ]
