# Generated by Django 4.1.3 on 2022-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_categorie_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
