# Generated by Django 4.1.3 on 2022-12-23 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_image_defaultanswer_answer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(validators=[quiz.models.validate_url])),
                ('embed_id', models.CharField(max_length=190)),
                ('sound_only', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='defaultanswer',
            name='answer_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_answer', to='quiz.video'),
        ),
        migrations.AddField(
            model_name='furtheranswer',
            name='answer_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_answer_option', to='quiz.video'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_question', to='quiz.video'),
        ),
    ]
