# Generated by Django 4.1.3 on 2022-11-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_last_edit_quiz_last_edit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_id', to='quiz.quiz'),
        ),
    ]
