# Generated by Django 4.1.3 on 2022-11-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_field_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_field', to='quiz.quiz'),
        ),
    ]
