# Generated by Django 4.1.3 on 2022-11-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_author_quiz_author_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='field',
            constraint=models.UniqueConstraint(fields=('quiz', 'question'), name='unique_question_quiz'),
        ),
    ]
