# Generated by Django 4.1.3 on 2022-11-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_field_unique_question_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='question',
            name='multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple choice'), ('SC', 'Simple question'), ('EQ', 'Estimation question')], default='SC', max_length=2),
        ),
        migrations.CreateModel(
            name='FurtherAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='default_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.defaultanswer'),
        ),
    ]
