# Generated by Django 4.1.3 on 2022-11-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_defaultanswer_remove_question_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furtheranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.defaultanswer'),
            preserve_default=False,
        ),
    ]
