# Generated by Django 4.1.3 on 2022-11-22 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_furtheranswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furtheranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_option', to='quiz.question'),
        ),
    ]
