# Generated by Django 4.1.3 on 2022-12-11 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0012_alter_field_categorie_alter_field_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
