# Generated by Django 4.1.3 on 2022-12-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_categorie_author'),
        ('quiz', '0014_alter_question_question_text'),
    ]

    operations = [
    ]
